name = "unison-landing-api"
main = "index.ts"
compatibility_date = "2026-03-05"

[[d1_databases]]
binding = "DB"
database_name = "unison-waitlist"
database_id = "a3325aa8-3cb0-435c-beb9-aa1cd4be3931"
